import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Main } from "@/lib/logic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>KEITH HÖRLING | Creator / Engineer / Leader</title>
        <link rel="icon" href="favicon.ico" type="image/png" />
        <link
          href="https://fonts.googleapis.com/css?family=Reem+Kufi|Roboto:300"
          rel="stylesheet"
        />
        <link
          href="https://use.fontawesome.com/releases/v6.4.0/css/all.css"
          rel="stylesheet"
        />
        <link rel="canonical" href="https://hoerling.com" />
        <meta name="robots" content="index, follow" />
        <meta charSet="utf-8" />
        <meta content="IE=edge,chrome=1" httpEquiv="X-UA-Compatible" />
        <meta
          name="viewport"
          content="user-scalable=0, initial-scale=1, maximum-scale=1, width=device-width, minimal-ui"
        />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="apple-mobile-web-app-title" content="Keith Hoerling" />
        <meta
          name="keywords"
          content="Keith Hoerling Mobile App & Web Development"
        />
        <meta itemProp="name" content="Keith Hoerling" />
        <meta
          name="description"
          itemProp="description"
          content="Software Consulting ⚡ on Silicon Beach, Los Angeles."
        />
        <meta property="og:title" content="Keith Hoerling" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://hoerling.com" />
        <meta
          property="og:description"
          content="Los Angeles, Silicon Beach-based Software Consulting & Engineering by Keith Hoerling"
        />
        <meta property="og:site_name" content="Keith Hoerling's Resume" />
        <link
          rel="alternate"
          type="application/atom+xml"
          title="Dimension Software Blog Posts"
          href="https://dimensionsoftware.com/static/feed.xml"
        />
        <link
          rel="alternate"
          type="application/rss+xml"
          title="Call to Action Podcast by Dimension Software"
          href="https://dimensionsoftware.com/static/podcast.xml"
        />
        <meta itemProp="image" content="/images/apple-touch-icon-114x114.png" />
        <meta itemProp="image" content="/images/apple-touch-icon-72x72.png" />
        <link
          href="/images/apple-touch-icon-114x114.png"
          rel="apple-touch-icon"
        />
        <link
          href="/images/apple-touch-icon-72x72.png"
          sizes="72x72"
          rel="apple-touch-icon"
        />
        <link
          href="/images/apple-touch-icon-114x114.png"
          sizes="114x114"
          rel="apple-touch-icon"
        />
      </head>

      <body
        id="app"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="plaid"></div>
        {children}
        <footer className="footer">
          <span className="glyph"></span>
          <span className="keith"></span>
        </footer>
        <Main />
      </body>
    </html>
  );
}
